In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import numpy as np
a=np.array([[1,2,3],[8,4,5]])
print(a)

[[1 2 3]
 [8 4 5]]


In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a[1])
print(a[0])

2
1


In [4]:
import numpy as np
b=np.array([1,8,9,5])
print(b+2)
print(b*3)
print(b ** 2)
print(b-2)
print(b/2)

[ 3 10 11  7]
[ 3 24 27 15]
[ 1 64 81 25]
[-1  6  7  3]
[0.5 4.  4.5 2.5]


In [5]:
import numpy as np
c=np.array([10,15,20,25,30])
print(np.sum(c))
print(np.max(c))
print(np.min(c))
print(np.mean(c))
print(np.zeros(5))
print(np.ones(5))

100
30
10
20.0
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [6]:
import numpy as np
a=np.array([2,5,6,8,7,8])
b=a.reshape(2,3)
print(b)
c=a.reshape(6,1)
print(c)

[[2 5 6]
 [8 7 8]]
[[2]
 [5]
 [6]
 [8]
 [7]
 [8]]


In [7]:
import numpy as np
a=np.arange(1,10,2)
print(a)
b=np.array([10,20,30,40])
print(b[1:3])
print(b[2:0:-1])


[1 3 5 7 9]
[20 30]
[30 20]


In [8]:
import numpy as np
a=np.array([[2,3],[4,5]])
b=np.array([[3,6],[1,2]])
print(a+b)
print(a-b)
print(np.dot(a,b))

[[5 9]
 [5 7]]
[[-1 -3]
 [ 3  3]]
[[ 9 18]
 [17 34]]


In [9]:
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 3)
6


In [10]:
import numpy as np
a=np.array([10,20,34,67])
a[1]=12
print(a)
b=np.array([[1,2,3],[5,6,7]])
print(b[1,2])
print(b[0:2,1:2])
c=np.array([45,67,9,55,34])
print(np.sort(c))

[10 12 34 67]
7
[[2]
 [6]]
[ 9 34 45 55 67]


In [11]:
import numpy as np
a=np.random.randint(1,100,2)
print(a)
b=np.array([1,2,1,2,5,5,5,7,8])
print(np.unique(b))

[23 20]
[1 2 5 7 8]
